on:
  delete:
    branches:
      - "**"

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      WORKSPACE_NAME: ${{github.ref_name}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.ref}}
      - run: find .
